############################
## CHANGE THESE
############################

baseURL: "https://DSamuelHodge.github.io/dsamuelhodge.github.io"
title: dsamuelhodge.github.io

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
