############################
## CHANGE THESE
############################

baseURL: "https://dsamuelhodge.github.io/"
title: "DSamuel Hodge"

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

theme: "qubt"
