author: "DSamuel Hodge"
description: "Personal website and blog focused on AI, machine learning, and software development"

social:
  github: "DSamuelHodge"

footer:
  since: 2025
  powered: true

features:
  darkMode: true
  syntaxHighlight: true
